### ISSUE TITLE
代码复现的正确率

### ISSUE THREAD

**Issue by xiangzhang06** [songdejia/DFL-CNN#3]
Hello, thank you very much for sharing the code, why I use your code training only 42%

**Comment by fxle** [comment]
@xiangzhang06 Hello，When I try to train this code .The following problems are appeared.Do you know how to solve it? Thanks
/home/steven/Documents/test/DFL-CNN/main.py
DFL-CNN <==> Part1 : prepare for parameters <==> Begin
DFL-CNN <==> Part1 : prepare for parameters <==> Done
DFL-CNN <==> Part2 : Load Network  <==> Begin
DFL-CNN <==> Part2 : Load Network  <==> Done
DFL-CNN <==> Part3 : Load Dataset  <==> Begin
Traceback (most recent call last):
  File "/home/steven/Documents/test/DFL-CNN/main.py", line 180, in <module>
    main() 
  File "/home/steven/Documents/test/DFL-CNN/main.py", line 121, in main
    dataroot = os.path.abspath(args.dataroot)
  File "/usr/lib/python3.5/posixpath.py", line 357, in abspath
    if not isabs(path):
  File "/usr/lib/python3.5/posixpath.py", line 64, in isabs
    return s.startswith(sep)
AttributeError: 'NoneType' object has no attribute 'startswith'

Process finished with exit code 1

**Comment by songdejia** [comment]
@xiangzhang06  Thank you for your reply.  Specific loss weights is not '1:1:1', you can try to tune it.

**Comment by songdejia** [comment]
@fxle --dataroot  /PATH/TO/YOUR_DATA

**Comment by pengshiqi** [comment]
@xiangzhang06  I got the same result as yours. Sad...
Have you met the overfitting problem? i.e. Accuracy on train set is 100% while accuracy on test set is only ~48%?

**Comment by xiangzhang06** [comment]
Yes, I have the same problem as you. How did you solve it  ? @pengshiqi

**Comment by wsqat** [comment]
Yes, I have the same problem as you. How did you solve it ? @pengshiqi
